### ISSUE TITLE
Packete epic und eepic

### ISSUE THREAD

**Issue by fkalweit** [MBrill/StylesAndMore#3]
Ich musste die zwei Packete **epic** und **eepic** manuell herunterladen und in meinen _texfm_ Ordner legen. Ist das normal oder ein Fehler in meiner LeTeX Umgebung?

**Comment by kfkonrad** [comment]
`epic` ist durch `eepic` ersetzt worden, das kann man der [Beschreibung im CTAN](https://ctan.org/pkg/epic) entnehmen. `epic` ist nur in MikTeX enthalten.
`eepic` (extended epic) ist [laut CTAN](https://ctan.org/pkg/eepic) sowohl in TeXLive als auch MikTeX enthalten.

Den jeweils im CTAN verlinkten Dokumentationen kann man übrigens entnehmen, dass `epic` seit 1986 und `eepic` **seit 1988 nicht mehr weiterentwickelt** wurde.  Die Pakete stammen aus der Ära von LaTeX 2.09 und **PDF gibt es auch erst seit 1993**. Beide Pakete sind nur zusammen mit DVI-Treibern nutzbar, da sie DVI-Features für den Einsatz von Bildern verwenden. Ein Einsatz mit `pdflatex`, `xelatex` oder `lualatex` ist nicht sinnvoll, da mit diesen modernen Engines/Compilern immer PDFs erzeugt werden.

*tl;dr:* Ja, das ist ein Fehler in deiner LaTeX Umgebung, aber das ist nicht weiter schlimm, weil man die Pakete ohnehin meiden sollte.
